apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
 name: hpa-nodeapis
 namespace: ecol
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: nodeapis
 minReplicas: 1
 maxReplicas: 10
 targetCPUUtilizationPercentage: 70