---
apiVersion: v1
kind: Service
metadata:
  name: birt-svc
  namespace: ecol
  labels:
    app: birt
spec:
  selector:
    app: birt
  ports:
    - protocol: TCP
      port: 8080
      name: 8080-tcp
      nodePort: 32273
  type: NodePort
--- 
# kubectl -n ecol create configmap server-xml-cm --from-file=../birt/server.xml
# kubectl -n ecol create configmap context-xml-cm --from-file=../birt/context.xml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: birt
  namespace: ecol
  labels:
    app: birt
spec:
  replicas: 2
  selector:
    matchLabels:
      app: birt
  template:
    metadata:
      labels:
        app: birt
    spec:
      containers:
      - name: birt
        image: migutak/birt:25072022.2
        volumeMounts:
        - name: server-xml-volume
          mountPath: /usr/local/tomcat/conf/server.xml
        - name: context-xml-volume
          mountPath: /usr/local/tomcat/conf/context.xml
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "100Mi"
            cpu: '100m'
          limits:
            memory: "1Gi"
            cpu: '500m'
      volumes:
      - name: server-xml-volume
        configMap:
          name: server-xml-cm
      - name: context-xml-volume
        configMap:
          name: context-xml-cm
      imagePullSecrets:
      - name: reg-cred-secret
      