apiVersion: batch/v1
kind: CronJob
metadata:
  name: utilizationrpt
  namespace: ecol
spec:
  schedule: "0 0 6 * * *"      #everyday 30th
  concurrencyPolicy: "Replace"  
  startingDeadlineSeconds: 200  
  suspend: false              
  successfulJobsHistoryLimit: 3 
  failedJobsHistoryLimit: 3     
  jobTemplate:                  
    spec:
      template:
        metadata:
          labels:               
            app: cachetqall
        spec:
          containers:
          - name: cachetqall-cron
            image: 172.16.204.72:5100/cache:5.7
            command: ["node",  "loader_tqall.js"]
            envFrom:
          - configMapRef:
              name: ecol-config
          - secretRef:
                name: ecol-secrets
          restartPolicy: OnFailure 
