apiVersion: v1
kind: Service
metadata:
  name: cacheapi-svc
  namespace: ecol
spec:
  selector:
    app: cacheapi
  ports:
    - protocol: TCP
      port: 5600
      name: 5600-tcp
      targetPort: 5600
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cacheapi
  namespace: ecol
  labels:
    app: cacheapi
spec:
  replicas: 4
  selector:
    matchLabels:
      app: cacheapi
  template:
    metadata:
      labels:
        app: cacheapi
    spec:
      containers:
      - name: cacheapi
        image: ecollect-registry.co-opbank.co.ke:30388/cache:18072022151323.2
        envFrom:
          - configMapRef:
              name: ecol-config
          - secretRef:
                name: ecol-secrets
        ports:
        - containerPort: 5600
        resources:
          requests:
            memory: "200Mi"
            cpu: '100m'
          limits:
            memory: "1Gi"
            cpu: '200m'
      imagePullSecrets:
      - name: reg-cred-secret
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
 name: hpa-cacheapi
 namespace: ecol
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: cacheapi
 minReplicas: 4
 maxReplicas: 10
 targetCPUUtilizationPercentage: 70 