apiVersion: batch/v1
kind: CronJob
metadata:
  name: dailychecksemail
  namespace: ecol
spec:
  schedule: "0 7 * * *"      #everyday at 7am 
  concurrencyPolicy: "Replace"  
  startingDeadlineSeconds: 200  
  suspend: false              
  successfulJobsHistoryLimit: 3 
  failedJobsHistoryLimit: 3     
  jobTemplate:                  
    spec:
      template:
        metadata:
          labels:               
            app: dailychecksemail
        spec:
          containers:
          - name: dailychecksemail
            image: ecollect-registry.co-opbank.co.ke:30677/dailychecksemail:18072022160825.2
            command: ["node",  "index.js"]
            envFrom:
          - configMapRef:
              name: ecol-config
          - secretRef:
                name: ecol-secrets
          restartPolicy: OnFailure 
