apiVersion: v1
kind: ConfigMap
metadata:
  name: ecol-config
  namespace: ecol
data:
  CONNECTIONSTRING: copkprdcont3-scan.co-opbank.co.ke:1559/ECOLLECT
  NODE_ORACLEDB_CONNECTIONSTRING: copkprdcont3-scan.co-opbank.co.ke:1559/ECOLLECT
  DB_DATABASE: ECOLLTST
  DB_PORT: '1559'
  DB_HOST: copkprdcont3-scan.co-opbank.co.ke
  REDISSVC: redis-svc.ecol.svc.cluster.local
  REDISPORT: '6379'
  NODEAPIURL: http://nodeapis-svc.ecol.svc.cluster.local:6001
  NODEAPI: http://nodeapis-svc.ecol.svc.cluster.local:6001
  URL: http://ecollectapis-svc.ecol.svc.cluster.local:8000
  MINIO_ENDPOINT: '172.16.204.74'
  FILEPATH: /tmp/
  IMAGEPATH: /app/docxletters/routes
  SENDEMAILURL: http://node-email-svc.ecol.svc.cluster.local:8005/ipfcancellation/email
  SMTPSERVER: smtp.office365.com
  SMTPPORT: '587'
  SMTPUSER: ecollecttest@co-opbank.co.ke
  PASS: abcd.123
  footerfirst: 'Directors: John Murugu (Chairman), Dr. Gideon Muriuki (Group M.D & CEO), M. Malonza (Vice Chairman), '
  footersecond: 'J. Sitienei, B. Simiyu, P. Githendu, W. Ongoro, R. Kimanthi, W. Mwambia, W. Welton (Mrs), M. Karangatha (Mrs), L. Karissa, G. Mburia'
  footersecond: 'Directors: John Murugu (Chairman), Dr. Gideon Muriuki (Group M.D & CEO), M. Malonza (Vice Chairman), J. Sitienei, B. Simiyu, P. Githendu, W.Ongoro, R.Kimanthi, W. Mwambia, W. Welton (Mrs), M. Karangatha (Mrs), L. Karissa, G. Mburia'
  MONGODB: mongodb://mongodb-svc.ecol.svc.cluster.local/mongorest
  FROM: ecollect@co-opbank.co.ke
  TO: ecollect@co-opbank.co.ke
  SERVERURL: http://172.16.204:9000
  RABBITMQ: amqp://rabbitmq.ecol.svc.cluster.local
  ELASTICSEARCH: http://es-svc.ecol.svc.cluster.local:9200/
  MINIO_PORT: '9005'
  TOEMAIL: 'marithi@co-opbank.co.ke,vomwega@co-opbank.co.ke,fkioko@co-opbank.co.ke'